name: Docker Image Build
on: 
  push:
    branches:
      - "latest"
      - "8.2"
      - "8.3"

jobs:
  build-cli:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USR }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and Push Base Image
        uses: docker/build-push-action@v4
        with:
          context: ./base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/addeeandra/php-xdebug:${{ github.head_ref }}
      - name: Build and Push Swoole Image
        uses: docker/build-push-action@v4
        with:
          context: ./swoole
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/addeeandra/php-xdebug:${{ github.head_ref }}-swoole
          build-args: |
            BASE_VERSION=${{ github.head_ref }}